Repository jorgeariasmartin/OceanLux-Backend, pull requests merged in 2025-02, with the labels that each got.

#5 ✨ Feature/authentication
  composer.json
  config/bundles.php
  src/Controller/LoginController.php
Labels: enhancement

#8 Create trip controller and fix bugs
  composer.json
  config/packages/doctrine.yaml
  config/packages/framework.yaml
  config/packages/security.yaml
  src/Controller/TripController.php
  src/Controller/YachtController.php
  src/Entity/Client.php
  src/Entity/Trip.php
  src/Entity/UserAccount.php
  src/Entity/Yacht.php
  src/Repository/YachtRepository.php
Labels: enhancement

#9 refactor tripcontroller
  src/Controller/TripController.php
Labels: Refactor

#10 fix security and some bugs
  config/packages/nelmio_cors.yaml
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/LoginController.php
  src/Controller/TripController.php
  src/Controller/UserController.php
  src/Controller/YachtController.php
  src/Entity/UserAccount.php
  src/Entity/Yacht.php
  src/Enum/Role.php
Labels: bug

#14 🐛 fix bugs
  src/Controller/TripController.php
  src/Controller/YachtController.php
Labels: bug
